### ISSUE TITLE
Video Streaming not working

### ISSUE THREAD

**Issue by inf1981** [CoyoteProd/libsumo.net#1]
Hi,

I got the code running, but video streaming is not working. I'm trying to understand the code and also changing some stuff, but I'm wondering if you looked into streaming?

Greetings
Mathias

**Comment by joseluisct** [comment]
Hi,

I am also trying to make video available but still no sucess. I have basic movement and animations working but have problems because sometimes is disconnected. 

Do you have any improvements?

I' ve made a new .net standard library, copy the code and now it works on all .net platforms, UWP, xamarin, ASP, desktop... I could make a pull request with changes.

Thanks.

**Comment by CoyoteProd** [comment]
New version just committed
